version: '3.0'

services:
  app:
    container_name: nussknacker_app
    image: ${NUSSKNACKER_IMAGE-touk/nussknacker}:${NUSSKNACKER_VERSION-staging-latest}
    volumes:
      - nussknacker_storage_app:/opt/nussknacker/storage

volumes:
  nussknacker_storage_app:
